put /manager/plastics/accept HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "token": 1,

}

###
get /manager/plastics HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "token": 1,

}

###
post /user/login HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "userId": "abc",
    "password": "abc"
}

###
post /manager/registration HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "userId": "abc",
    "password": "abc",
    "email": "manager@example.com",
    "name": "manager"
}

###
put /manager/plastics/accept HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhYmMiLCJ1c2VyUm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MTE4Nzg5ODYsImV4cCI6MTcxMTg4MjU4Nn0.GE40gdN44kBZbgDOc3bCWxZIDwI5X8elIf4bbnPunuY

{
    "token": 1,

}

###
post /user/orders HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhYmMiLCJpYXQiOjE3MTE4ODA3ODAsImV4cCI6MTcxMTg4NDM4MH0.bW92zuB4eIWefsn73eZ9z1QNcRVsl0SHBU7DkxhiIq0

{
    "date": "2021-01-01",
    "itemName": "pepsi",
    "quantity": 1
}



###
post /cooking_staff/registration HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "userId": "abc",
    "password": "abc",
    "email": "abc@email.com",
    "name": "abc"
}